#!/bin/sh
# SPDX-License-Identifier: MIT

set -x
if [ ! -d "config" ]; then
	mkdir config
fi

# Run autoreconf with all warning types as errors except
# for 'obsolete' because of AM_PATH_GLIB_2_0
autoreconf -vif -W all,error,no-obsolete
