#!/bin/sh
# SPDX-License-Identifier: MIT

set -x
if [ ! -d "config" ]; then
	mkdir config
fi

# Run autoreconf with all warning types as errors except
# for 'obsolete' because of AM_PATH_GLIB_2_0, we have to
# list all categories because when 'all' is used, autoreconf
# will drop all the other specified categories except 'error'
# even if they start with 'no-'.
autoreconf -vif -W cross,gnu,no-obsolete,override,portability,portability-recursive,extra-portability,syntax,unsupported,error
