#!/bin/bash
#
# Copyright (C) 2019 Simon Marchi <simon.marchi@efficios.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License, version 2 only, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Test the auto source disovery mechanism of the CLI.

if [ "x${BT_TESTS_SRCDIR:-}" != "x" ]; then
	UTILSSH="$BT_TESTS_SRCDIR/utils/utils.sh"
else
	UTILSSH="$(dirname "$0")/../../utils/utils.sh"
fi

# shellcheck source=../../utils/utils.sh
SH_TAP=1 source "$UTILSSH"

NUM_TESTS=1

plan_tests $NUM_TESTS

data_dir="${BT_TESTS_DATADIR}/cli/convert/auto-source-discovery-grouping"
plugin_dir="${data_dir}"
trace_dir="${data_dir}/traces"

if [ "$BT_OS_TYPE" = "mingw" ]; then
	# Use Windows native paths for comparison because Unix
	# paths are converted by the shell before they are passed
	# to the native babeltrace2 binary.
	trace_dir=$(cygpath -w "$trace_dir")
	dir_sep='\'
else
	dir_sep='/'
fi

expected_file=$(mktemp -t expected.XXXXXX)
stderr_expected=/dev/null

cat > "$expected_file" <<END
TestSourceABCDE: ABCDE
TestSourceExt: ${trace_dir}${dir_sep}aaa1, ${trace_dir}${dir_sep}aaa2, ${trace_dir}${dir_sep}aaa3
TestSourceExt: ${trace_dir}${dir_sep}bbb1, ${trace_dir}${dir_sep}bbb2
TestSourceExt: ${trace_dir}${dir_sep}ccc1
TestSourceExt: ${trace_dir}${dir_sep}ccc2
TestSourceExt: ${trace_dir}${dir_sep}ccc3
TestSourceExt: ${trace_dir}${dir_sep}ccc4
TestSourceSomeDir: ${trace_dir}${dir_sep}some-dir
END

bt_diff_cli_sorted "$expected_file" "$stderr_expected" convert --plugin-path "${plugin_dir}" "ABCDE" "${trace_dir}" some_other_non_opt
ok "$?" "sources are auto-discovered"

rm -f "$expected_file"
